# Generated by Django 5.0.6 on 2024-07-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_backend', '0002_cliente_oferta_producto_delete_yourmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
